export const GET_All_USERS = "GET_All_USERS";
export const GET_All_USERS_SUCCED = "GET_All_USERS_SUCCED";
export const GET_All_USERS_FAILED = "GET_All_USERS_FAILED";

export const ADD_ONE_USER = "ADD_ONE_USER";
export const ADD_ONE_USER_SUCCED = "ADD_ONE_USER_SUCCED";
export const ADD_ONE_USER_FAILED = "ADD_ONE_USER_FAILED";

export const EDIT_ONE_USER = "EDIT_ONE_USER";
export const EDIT_ONE_USER_SUCCED = "EDIT_ONE_USER_SUCCED";
export const EDIT_ONE_USER_FAILED = "EDIT_ONE_USER_FAILED";

export const DELETE_ONE_USER = "DELETE_ONE_USER";
export const DELETE_ONE_USER_SUCCED = "DELETE_ONE_USER_SUCCED";
export const DELETE_ONE_USER_FAILED = "DELETE_ONE_USER_FAILED";
